<?php
require 'config.php';
require_user();
if (($_GET['legacy'] ?? '') !== '1') {
    redirect('/websites.php');
}
$uid=$_SESSION['user_id'];
$orders=$pdo->prepare('SELECT * FROM orders WHERE user_id=? ORDER BY id DESC'); $orders->execute([$uid]);
$hosts=$pdo->prepare('SELECT * FROM hosting_accounts WHERE user_id=? ORDER BY id DESC'); $hosts->execute([$uid]);
$cf=$pdo->prepare('SELECT * FROM cloudflare_accounts WHERE user_id=? ORDER BY id DESC LIMIT 1'); $cf->execute([$uid]); $cfRow=$cf->fetch();
?>
<!doctype html><html><head><title>Customer Dashboard</title><link rel="stylesheet" href="/style.css"><meta name="viewport" content="width=device-width,initial-scale=1"></head><body><div class="dash"><div class="side"><h2>Karacraft</h2><a href="/dashboard.php">Dashboard</a><a href="/domains.php">Domains</a><a href="/order.php">Order Hosting</a><a href="/billing.php">Billing</a><a href="/support.php">Support</a><a href="/migration.php">Migration</a><a href="/logout.php">Logout</a></div><div class="main"><h1>Welcome, <?=h($_SESSION['user_name'])?></h1><?=render_flash()?><div class="grid"><div class="card"><h3>Domains</h3><p class="muted">Connect your own domain, verify DNS, sync Cloudflare, and repair routing.</p><a class="btn" href="/domains.php">Manage Domains</a></div><div class="card"><h3>Order Hosting</h3><p class="muted">Choose a plan and submit payment reference.</p><a class="btn" href="/order.php">New Order</a></div><div class="card"><h3>Upload Guide</h3><p class="muted">Upload with File Manager or use ZIP Upload. The platform extracts the archive and repairs permissions automatically.</p></div></div>
<div class="card"><h2>Cloudflare Settings</h2><p class="muted">Connect Cloudflare to sync and repair DNS records for your custom domains.</p><form class="wide-form" method="post" action="/cloudflare_action.php"><?=csrf_field()?><input type="hidden" name="action" value="save"><label>API Token</label><input name="api_token" type="password" placeholder="<?=h($cfRow ? 'Saved - enter a new token to replace' : 'Cloudflare API token')?>" <?php if(!$cfRow) echo 'required'; ?>><label>Zone ID optional</label><input name="zone_id" value="<?=h($cfRow['zone_id'] ?? '')?>"><button class="btn small">Save Cloudflare</button></form><div class="actions"><form class="inline" method="post" action="/cloudflare_action.php"><?=csrf_field()?><input type="hidden" name="action" value="verify_connection"><button class="btn small">Verify Connection</button></form><form class="inline" method="post" action="/cloudflare_action.php"><?=csrf_field()?><input type="hidden" name="action" value="sync_dns"><button class="btn small">Sync DNS</button></form><form class="inline" method="post" action="/cloudflare_action.php"><?=csrf_field()?><input type="hidden" name="action" value="repair_dns"><button class="btn small warn">Repair DNS</button></form></div><small>Status: <?=h($cfRow['status'] ?? 'not connected')?> | Last check: <?=h($cfRow['last_check_at'] ?? '-')?></small></div>
<h2>My Hosting Control Center</h2>
<?php foreach($hosts as $row): $plan=plan_details($row['plan']); $sitePath=site_path_for($row); $storage=get_du_bytes($sitePath); $dbsize=db_size_bytes($pdo,$row['db_name']); $storageLimit=($row['storage_limit_mb'] ?: $plan['storage_mb'])*1024*1024; $dbLimit=($row['db_limit_mb'] ?: $plan['db_mb'])*1024*1024; $siteState=container_state($row['container_name']); $fbState=container_state($row['filebrowser_container']); $stats=docker_stats($row['container_name']); $domains=$pdo->prepare('SELECT * FROM custom_domains WHERE hosting_account_id=? ORDER BY id DESC'); $domains->execute([$row['id']]); ?>
<div class="card account-card">
  <div class="account-head"><div><h2><?=h(ucfirst($row['plan']))?> Hosting</h2><p class="muted">Expires: <?=h($row['expires_at'] ?: 'Not set')?> | Status: <?=h($row['status'])?></p></div><span class="badge <?=h($row['status'])?>"><?=h($row['status'])?></span></div>
  <div class="grid four">
    <div><h3>Website</h3><p>Status: <strong><?=h($siteState)?></strong></p><p><a class="btn small" href="<?=h($row['site_url'])?>" target="_blank">Open Website</a></p><small>Container: <?=h($row['container_name'])?></small></div>
    <div><h3>File Manager</h3><p>Status: <strong><?=h($fbState)?></strong></p><p><a class="btn small" href="<?=h($row['filebrowser_url'])?>" target="_blank">Open File Manager</a></p><small>Username: <?=h($row['filebrowser_username'])?><br>Password: <span class="secret"><?=h($row['filebrowser_password'])?></span></small></div>
    <div><h3>Database</h3><small>Host: hosting-platform-db<br>Port: 3306<br>Name: <?=h($row['db_name'])?><br>User: <?=h($row['db_user'])?><br>Password: <span class="secret"><?=h($row['db_password'])?></span></small><p><a class="btn small" href="<?=h($row['phpmyadmin_url'])?>" target="_blank">Open phpMyAdmin</a></p></div>
    <div><h3>Live Metrics</h3><small>CPU: <?=h($stats['cpu'])?><br>RAM: <?=h($stats['mem'])?><br>Network: <?=h($stats['net'])?><br>Disk I/O: <?=h($stats['block'])?></small></div>
  </div>
  <div class="usage-row"><label>Storage Used: <?=fmt_bytes($storage)?> / <?=fmt_bytes($storageLimit)?> | Files: <?=h(file_count($sitePath))?></label><div class="bar"><span style="width:<?=pct($storage,$storageLimit)?>%"></span></div></div>
  <div class="usage-row"><label>Database Used: <?=fmt_bytes($dbsize)?> / <?=fmt_bytes($dbLimit)?></label><div class="bar"><span style="width:<?=pct($dbsize,$dbLimit)?>%"></span></div></div>
  <div class="card soft"><h3>Domain Information</h3><p><strong>Temporary Website:</strong> <a href="<?=h($row['site_url'])?>" target="_blank"><?=h($row['site_domain'] ?: $row['site_url'])?></a></p><p><strong>Temporary File Manager:</strong> <a href="<?=h($row['filebrowser_url'])?>" target="_blank"><?=h($row['filebrowser_domain'] ?: $row['filebrowser_url'])?></a></p><?php foreach($domains as $d):?><p><strong><?=h(ucfirst($d['domain_type']))?> domain:</strong> <?=h($d['domain'])?> <span class="badge <?=h($d['verification_status'])?>"><?=h($d['verification_status'])?></span><br><small>CNAME/ALIAS target: <?=h($d['dns_target'])?><br>TXT verification: <?=h($d['verification_token'])?><br>Routing: <?=h($d['routing_status'] ?: 'pending')?> | Cloudflare: <?=h($d['cloudflare_status'] ?: 'pending')?> | SSL: <?=h($d['ssl_status'] ?: 'pending')?> | Last check: <?=h($d['last_checked_at'] ?: '-')?></small></p><form class="inline" method="post" action="/domain_action.php"><?=csrf_field()?><input type="hidden" name="action" value="verify"><input type="hidden" name="id" value="<?=h($d['id'])?>"><button class="btn small">Verify Domain</button></form><form class="inline" method="post" action="/domain_action.php"><?=csrf_field()?><input type="hidden" name="action" value="repair"><input type="hidden" name="id" value="<?=h($d['id'])?>"><button class="btn small warn">Repair Domain</button></form><form class="inline" method="post" action="/domain_action.php"><?=csrf_field()?><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?=h($d['id'])?>"><button class="btn small danger" onclick="return confirm('Remove this custom domain?')">Remove Domain</button></form><?php endforeach;?><form class="wide-form" method="post" action="/domain_action.php"><?=csrf_field()?><input type="hidden" name="action" value="add"><input type="hidden" name="hosting_account_id" value="<?=h($row['id'])?>"><label>Add custom domain</label><input name="domain" placeholder="example.com or www.example.com" required><label>Use for</label><select name="domain_type"><option value="website">Website</option><option value="filemanager">File Manager</option></select><button class="btn small">Add Domain</button></form><p class="muted">Point the domain to the CNAME/ALIAS target shown, then click Verify Domain. Verified domains are added to the live Traefik route for this hosting account.</p></div>
  <?php $zipFiles=[]; foreach(glob($sitePath.'/_uploads/*.zip') ?: [] as $zf){ $zipFiles[]='_uploads/'.basename($zf); } foreach(glob($sitePath.'/*.zip') ?: [] as $zf){ $zipFiles[]=basename($zf); } ?>
  <div class="card soft"><h3>ZIP Upload + Extract</h3><form method="post" action="/user_action.php" enctype="multipart/form-data"><?=csrf_field()?><input type="hidden" name="id" value="<?=h($row['id'])?>"><input type="hidden" name="action" value="zip_upload_only"><input type="file" name="zip_file" accept=".zip" required><button class="btn small">Upload ZIP</button></form><?php if($zipFiles):?><form method="post" action="/user_action.php" class="wide-form"><?=csrf_field()?><input type="hidden" name="id" value="<?=h($row['id'])?>"><input type="hidden" name="action" value="extract_zip"><label>Select ZIP to extract</label><select name="zip_path"><?php foreach($zipFiles as $zf):?><option value="<?=h($zf)?>"><?=h($zf)?></option><?php endforeach;?></select><button class="btn small warn" onclick="return confirm('Extract selected ZIP, fix permissions, and restart website?')">Extract ZIP</button></form><?php endif;?><p class="muted">Extraction is restricted to your website folder and automatically repairs permissions and restarts the website.</p></div>
  <div class="card soft"><h3>Self-Service Controls</h3><p class="muted">Use these controls after uploading files, replacing index.html, or when your website/file manager needs a restart.</p><div class="actions">
    <form class="inline" method="post" action="/user_action.php"><?=csrf_field()?><input type="hidden" name="id" value="<?=h($row['id'])?>"><input type="hidden" name="action" value="restart_site"><button class="btn small" onclick="return confirm('Restart website and fix file permissions?')">Restart Website</button></form>
    <form class="inline" method="post" action="/user_action.php"><?=csrf_field()?><input type="hidden" name="id" value="<?=h($row['id'])?>"><input type="hidden" name="action" value="restart_filebrowser"><button class="btn small" onclick="return confirm('Restart File Manager?')">Restart File Manager</button></form>
    <form class="inline" method="post" action="/user_action.php"><?=csrf_field()?><input type="hidden" name="id" value="<?=h($row['id'])?>"><input type="hidden" name="action" value="fix_permissions"><button class="btn small" onclick="return confirm('Fix website file permissions?')">Fix Permissions</button></form>
    <form class="inline" method="post" action="/user_action.php"><?=csrf_field()?><input type="hidden" name="id" value="<?=h($row['id'])?>"><input type="hidden" name="action" value="reset_fb_password"><button class="btn small warn" onclick="return confirm('Reset File Manager password? The new password will show here after reset.')">Reset File Manager Password</button></form>
  </div><small>Last action: <?=h($row['last_action'] ?: 'None')?></small></div>
  <?php $backupRows=$pdo->prepare('SELECT * FROM backups WHERE hosting_account_id=? ORDER BY id DESC LIMIT 10'); $backupRows->execute([$row['id']]); ?>
  <div class="card soft"><h3>Backup & Restore</h3><form class="inline" method="post" action="/user_action.php"><?=csrf_field()?><input type="hidden" name="id" value="<?=h($row['id'])?>"><input type="hidden" name="action" value="backup"><button class="btn small">Create Backup</button></form><?php foreach($backupRows as $b):?><p><strong><?=h($b['backup_type'])?></strong> <?=h(fmt_bytes($b['file_size']))?> <small><?=h($b['created_at'])?></small></p><form class="inline" method="post" action="/user_action.php"><?=csrf_field()?><input type="hidden" name="id" value="<?=h($row['id'])?>"><input type="hidden" name="action" value="restore_backup"><input type="hidden" name="backup_id" value="<?=h($b['id'])?>"><button class="btn small danger" onclick="return confirm('Restore this backup over current data?')">Restore</button></form><?php endforeach;?></div>
</div>
<?php endforeach; ?>
<h2>My Orders</h2><table class="table"><tr><th>ID</th><th>Plan</th><th>Payment Ref</th><th>Status</th><th>Date</th></tr><?php foreach($orders as $o):?><tr><td>#<?=h($o['id'])?></td><td><?=h($o['plan'])?></td><td><?=h($o['payment_reference'])?></td><td><span class="badge <?=h($o['status'])?>"><?=h($o['status'])?></span></td><td><?=h($o['created_at'])?></td></tr><?php endforeach;?></table>
</div></div></body></html>
