<?php
require 'config.php';
require_user();
require '_customer_nav.php';
$uid=(int)current_user_id();
$id=(int)($_GET['id'] ?? 0);
$tab=$_GET['tab'] ?? 'overview';
$st=$pdo->prepare('SELECT * FROM hosting_accounts WHERE id=? AND user_id=?');
$st->execute([$id,$uid]);
$site=$st->fetch();
if(!$site) die('Website not found.');
$plan=plan_details($site['plan']);
$sitePath=site_path_for($site);
$storage=get_du_bytes($sitePath);
$dbsize=db_size_bytes($pdo,$site['db_name']);
$storageLimit=($site['storage_limit_mb'] ?: $plan['storage_mb'])*1024*1024;
$dbLimit=($site['db_limit_mb'] ?: $plan['db_mb'])*1024*1024;
$siteState=container_state($site['container_name']);
$fbState=container_state($site['filebrowser_container']);
$stats=docker_stats($site['container_name']);
$displayDomain=display_domain_for($pdo,$site,'website');
$displayUrl=display_url_for($pdo,$site,'website');
$fileUrl=display_url_for($pdo,$site,'filemanager');
?>
<!doctype html><html><head><title>Website Dashboard</title><link rel="stylesheet" href="/style.css"><meta name="viewport" content="width=device-width,initial-scale=1"></head><body><div class="dash"><?php customer_nav('websites'); ?><div class="main"><div class="account-head"><div><h1><?=h($displayDomain ?: 'Website #'.$site['id'])?></h1><p class="muted"><?=h(ucfirst($site['plan']))?> | Status: <?=h($site['status'])?> | Temporary: <?=h($site['site_domain'])?> | Expires: <?=h($site['expires_at'] ?: 'Not set')?></p></div><div><a class="btn small" target="_blank" href="<?=h($displayUrl)?>">Open Website</a><a class="btn small" target="_blank" href="<?=h($fileUrl)?>">File Manager</a></div></div><?=render_flash()?><?php website_tabs($site,$tab); ?>
<?php if($tab==='overview'): ?>
<div class="grid four"><div class="card stat"><span>Website</span><h1><?=h($siteState)?></h1></div><div class="card stat"><span>File Manager</span><h1><?=h($fbState)?></h1></div><div class="card stat"><span>CPU</span><h1><?=h($stats['cpu'])?></h1></div><div class="card stat"><span>RAM</span><h1><?=h($stats['memperc'])?></h1></div></div><div class="grid"><div class="card"><h3>Storage</h3><div class="usage-row"><label><?=h(fmt_bytes($storage))?> / <?=h(fmt_bytes($storageLimit))?></label><div class="bar"><span style="width:<?=h(pct($storage,$storageLimit))?>%"></span></div></div></div><div class="card"><h3>Database</h3><div class="usage-row"><label><?=h(fmt_bytes($dbsize))?> / <?=h(fmt_bytes($dbLimit))?></label><div class="bar"><span style="width:<?=h(pct($dbsize,$dbLimit))?>%"></span></div></div></div><div class="card"><h3>Quick Actions</h3><form class="inline" method="post" action="/user_action.php"><?=csrf_field()?><input type="hidden" name="id" value="<?=h($site['id'])?>"><input type="hidden" name="action" value="restart_site"><button class="btn small">Restart Website</button></form><form class="inline" method="post" action="/user_action.php"><?=csrf_field()?><input type="hidden" name="id" value="<?=h($site['id'])?>"><input type="hidden" name="action" value="fix_permissions"><button class="btn small">Fix Permissions</button></form></div></div>
<?php elseif($tab==='domains'): $domains=$pdo->prepare('SELECT * FROM custom_domains WHERE hosting_account_id=? ORDER BY id DESC'); $domains->execute([$site['id']]); ?>
<div class="step-list"><div class="step"><h3><strong>1</strong>Add Domain</h3><p class="muted">Enter the domain you want visitors to use.</p></div><div class="step"><h3><strong>2</strong>Add DNS</h3><p class="muted">Create the CNAME records shown below inside Cloudflare.</p></div><div class="step"><h3><strong>3</strong>Verify</h3><p class="muted">Click Verify after DNS is added. Click Repair if routing still says pending.</p></div></div><div class="guide-shots"><div class="guide-shot"><div class="browserbar"></div><h3>Cloudflare DNS</h3><div class="row"><strong>Type</strong><span>CNAME</span></div><div class="row"><strong>Name</strong><span>your subdomain</span></div><div class="row"><strong>Target</strong><span>site-...karacraft.ng</span></div></div><div class="guide-shot"><div class="browserbar"></div><h3>Proxy On</h3><div class="row"><strong>Proxy status</strong><span class="pill">Proxied</span></div><div class="row"><strong>TTL</strong><span>Auto</span></div><p class="muted">Keep the orange cloud enabled.</p></div><div class="guide-shot"><div class="browserbar"></div><h3>Back To Karacraft</h3><div class="row"><strong>Step</strong><span>Click Verify</span></div><div class="row"><strong>If pending</strong><span>Click Repair</span></div><p class="muted">Wait 1-5 minutes after DNS changes.</p></div></div><div class="card"><h2>Add Custom Domain</h2><form class="wide-form" method="post" action="/domain_action.php"><?=csrf_field()?><input type="hidden" name="action" value="add"><input type="hidden" name="hosting_account_id" value="<?=h($site['id'])?>"><label>Domain</label><input name="domain" placeholder="karashare.karacraft.ng" required><label>Use for</label><select name="domain_type"><option value="website">Website</option><option value="filemanager">File Manager</option></select><button class="btn small">Next: Show DNS Instructions</button></form></div><div class="card"><h2>Connect Domains</h2><table class="table"><tr><th>Domain</th><th>Cloudflare DNS Record</th><th>Status</th><th>Actions</th></tr><?php foreach($domains as $d):?><tr><td><strong><?=h($d['domain'])?></strong><br><small>TXT: <?=h($d['verification_token'])?></small></td><td><div class="dns-record"><strong>Add this CNAME in Cloudflare</strong><code>Type: CNAME
Name: <?=h(str_replace('.'.base_domain(), '', $d['domain']))?>
Target: <?=h($d['dns_target'])?>
Proxy: Proxied
TTL: Auto</code></div></td><td><span class="badge <?=h($d['verification_status'])?>"><?=h($d['verification_status'])?></span><br><small>Routing: <?=h($d['routing_status'] ?: 'pending')?> | SSL: <?=h($d['ssl_status'] ?: 'pending')?></small></td><td><form class="inline" method="post" action="/domain_action.php"><?=csrf_field()?><input type="hidden" name="action" value="verify"><input type="hidden" name="id" value="<?=h($d['id'])?>"><button class="btn small">Verify</button></form><form class="inline" method="post" action="/domain_action.php"><?=csrf_field()?><input type="hidden" name="action" value="repair"><input type="hidden" name="id" value="<?=h($d['id'])?>"><button class="btn small warn">Repair</button></form></td></tr><?php endforeach;?></table></div>
<?php elseif($tab==='files'): $zipFiles=[]; foreach(glob($sitePath.'/_uploads/*.zip') ?: [] as $zf){ $zipFiles[]='_uploads/'.basename($zf); } foreach(glob($sitePath.'/*.zip') ?: [] as $zf){ $zipFiles[]=basename($zf); } ?>
<?php if(isset($_GET['uploaded'])):?><div class="alert">ZIP uploaded. Select it below to extract.</div><?php endif; ?><?php if(isset($_GET['extracted'])):?><div class="alert">ZIP extracted, permissions repaired, and website restarted.</div><?php endif; ?><div class="grid"><div class="card"><h2>File Manager</h2><p><a class="btn" target="_blank" href="<?=h($fileUrl)?>">Open Karacraft Files</a></p><small>Username: <?=h($site['filebrowser_username'])?><br>Password: <span class="secret"><?=h($site['filebrowser_password'])?></span></small><div class="actions"><form class="inline" method="post" action="/user_action.php"><?=csrf_field()?><input type="hidden" name="id" value="<?=h($site['id'])?>"><input type="hidden" name="action" value="reset_fb_password"><button class="btn small warn" onclick="return confirm('Reset File Manager password? The new password will be shown here.')">Reset File Manager Password</button></form><form class="inline" method="post" action="/user_action.php"><?=csrf_field()?><input type="hidden" name="id" value="<?=h($site['id'])?>"><input type="hidden" name="action" value="restart_filebrowser"><button class="btn small">Restart File Manager</button></form></div></div><div class="card"><h2>ZIP Upload & Extract</h2><form method="post" action="/user_action.php" enctype="multipart/form-data"><?=csrf_field()?><input type="hidden" name="id" value="<?=h($site['id'])?>"><input type="hidden" name="action" value="zip_upload_only"><input type="file" name="zip_file" accept=".zip,application/zip,application/x-zip-compressed" required><button class="btn small">Upload ZIP</button></form><?php if($zipFiles):?><form class="wide-form" method="post" action="/user_action.php"><?=csrf_field()?><input type="hidden" name="id" value="<?=h($site['id'])?>"><input type="hidden" name="action" value="extract_zip"><label>Select ZIP</label><select name="zip_path"><?php foreach($zipFiles as $zf):?><option value="<?=h($zf)?>"><?=h($zf)?></option><?php endforeach;?></select><button class="btn small warn">Extract ZIP</button></form><?php endif;?></div></div>
<?php elseif($tab==='databases'): ?>
<div class="card"><h2>Database</h2><p><a class="btn small" target="_blank" href="<?=h($site['phpmyadmin_url'])?>">Open phpMyAdmin</a></p><table class="table"><tr><th>Host</th><td>hosting-platform-db</td></tr><tr><th>Database</th><td><?=h($site['db_name'])?></td></tr><tr><th>User</th><td><?=h($site['db_user'])?></td></tr><tr><th>Password</th><td><span class="secret"><?=h($site['db_password'])?></span></td></tr></table></div>
<?php elseif($tab==='backups'): $backups=$pdo->prepare('SELECT * FROM backups WHERE hosting_account_id=? ORDER BY id DESC'); $backups->execute([$site['id']]); ?>
<div class="card"><h2>Backups</h2><form method="post" action="/user_action.php"><?=csrf_field()?><input type="hidden" name="id" value="<?=h($site['id'])?>"><input type="hidden" name="action" value="backup"><button class="btn small">Create Backup</button></form><table class="table"><tr><th>Type</th><th>Size</th><th>Date</th><th>Restore</th></tr><?php foreach($backups as $b):?><tr><td><?=h($b['backup_type'])?></td><td><?=h(fmt_bytes($b['file_size']))?></td><td><?=h($b['created_at'])?></td><td><form method="post" action="/user_action.php"><?=csrf_field()?><input type="hidden" name="id" value="<?=h($site['id'])?>"><input type="hidden" name="action" value="restore_backup"><input type="hidden" name="backup_id" value="<?=h($b['id'])?>"><button class="btn small danger">Restore</button></form></td></tr><?php endforeach;?></table></div>
<?php elseif($tab==='security'): ?>
<div class="grid"><div class="card"><h2>SSL</h2><p class="muted">Cloudflare edge SSL is used for routed domains.</p><span class="badge pending">Managed by Cloudflare</span></div><div class="card"><h2>Force HTTPS</h2><p class="muted">Cloudflare should redirect visitors to HTTPS. Origin receives HTTP through Tunnel.</p></div><div class="card"><h2>Security Scan</h2><p class="muted">Malware scanning is planned for V6.1.</p><span class="badge pending">Coming next</span></div></div>
<?php elseif($tab==='performance'): ?>
<div class="grid"><div class="card"><h2>Resource Usage</h2><small>CPU: <?=h($stats['cpu'])?><br>RAM: <?=h($stats['mem'])?><br>Network: <?=h($stats['net'])?><br>Disk I/O: <?=h($stats['block'])?></small></div><div class="card"><h2>Cache/CDN</h2><p class="muted">Cloudflare cache purge and CDN controls are planned.</p></div></div>
<?php elseif($tab==='apps'): $apps=['wordpress'=>['WordPress','Blog/CMS. Fully preconfigured with your database.'],'moodle'=>['Moodle','Learning management system. Finish setup in browser.'],'opencart'=>['OpenCart','Ecommerce store. Finish setup in browser.'],'joomla'=>['Joomla','CMS. Finish setup in browser.'],'drupal'=>['Drupal','Advanced CMS. Finish setup in browser.'],'grav'=>['Grav','Fast flat-file CMS. No database needed.']]; ?>
<?php if(isset($_GET['reset'])):?><div class="alert">Website files and database were reset. You can install a fresh app now.</div><?php endif; ?><div class="card"><h2>Apps</h2><p class="muted">Install popular web apps into this website. Existing files may be overwritten.</p><div class="grid"><?php foreach($apps as $slug=>$meta):?><div class="card soft"><h3><?=h($meta[0])?></h3><p class="muted"><?=h($meta[1])?></p><form method="post" action="/app_action.php"><?=csrf_field()?><input type="hidden" name="id" value="<?=h($site['id'])?>"><input type="hidden" name="action" value="install_app"><input type="hidden" name="app" value="<?=h($slug)?>"><button class="btn small warn" onclick="return confirm('Install <?=h($meta[0])?>? Existing site files may be overwritten.')">Install</button></form></div><?php endforeach;?></div></div><div class="card danger-zone"><h2>Fresh Start</h2><p class="muted">Delete all website files, uploaded app data, and database tables for this hosting account. The hosting account, temporary domain, custom domains, file manager login, and database credentials stay the same.</p><form class="wide-form" method="post" action="/user_action.php"><?=csrf_field()?><input type="hidden" name="id" value="<?=h($site['id'])?>"><input type="hidden" name="action" value="reset_website"><label>Type RESET WEBSITE to confirm</label><input name="reset_confirm" placeholder="RESET WEBSITE" required><button class="btn small danger" onclick="return confirm('This will permanently delete this website files and reset its database. Continue?')">Reset Website</button></form></div>
<?php elseif($tab==='logs'): $logs=$pdo->prepare('SELECT * FROM activity_logs WHERE hosting_account_id=? ORDER BY id DESC LIMIT 100'); $logs->execute([$site['id']]); ?>
<div class="card"><h2>Activity Logs</h2><table class="table"><tr><th>Action</th><th>Details</th><th>Date</th></tr><?php foreach($logs as $l):?><tr><td><?=h($l['action'])?></td><td><?=h($l['details'])?></td><td><?=h($l['created_at'])?></td></tr><?php endforeach;?></table></div>
<?php elseif($tab==='support'): ?>
<div class="card"><h2>Support</h2><p class="muted">Open a support ticket for this website.</p><form class="wide-form" method="post" action="/support.php"><?=csrf_field()?><input type="hidden" name="hosting_account_id" value="<?=h($site['id'])?>"><label>Priority</label><select name="priority"><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option></select><label>Subject</label><input name="subject" required><label>Message</label><textarea name="message" required></textarea><button class="btn small">Submit Ticket</button></form></div>
<?php endif; ?>
</div></div></body></html>
