services:
  app_proxy:
    image: getumbrel/app-proxy:1.7.0
    environment:
      APP_HOST: karashare-web
      APP_PORT: 80
      PROXY_PORT: 3104
      PROXY_AUTH_ADD: "false"
      PROXY_AUTH_WHITELIST: ""
      PROXY_AUTH_BLACKLIST: ""
      LOG_LEVEL: info
      JWT_SECRET: c42c8a9ac2f2d1d67860467eb18dd40d71de9487ae35ae8a632e14fe59f30c6f
      MANAGER_IP: 10.21.21.4
      MANAGER_PORT: 3006
      UMBREL_AUTH_SECRET: DEADBEEF
      AUTH_SERVICE_PORT: 2000
    volumes:
      - ${APP_DATA_DIR}:/data
      - ${APP_DATA_DIR}/umbrel-app.yml:/extra/umbrel-app.yml:ro

  karashare-web:
    image: php:8.3-apache
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}:/var/www/html
    command: ["/bin/sh", "-ec", "a2enmod rewrite headers >/dev/null 2>&1 || true; apache2-foreground"]
